// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filter_data.proto

#include "filter_data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_filter_5fdata_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_FilterConfig_FilterMapEntry_DoNotUse_filter_5fdata_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_filter_5fdata_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FilterItem_filter_5fdata_2eproto;
namespace my_msg {
class FilterItemDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FilterItem> _instance;
} _FilterItem_default_instance_;
class FilterConfig_FilterMapEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FilterConfig_FilterMapEntry_DoNotUse> _instance;
} _FilterConfig_FilterMapEntry_DoNotUse_default_instance_;
class FilterConfigDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FilterConfig> _instance;
} _FilterConfig_default_instance_;
}  // namespace my_msg
static void InitDefaultsscc_info_FilterConfig_filter_5fdata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::my_msg::_FilterConfig_default_instance_;
    new (ptr) ::my_msg::FilterConfig();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::my_msg::FilterConfig::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_FilterConfig_filter_5fdata_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_FilterConfig_filter_5fdata_2eproto}, {
      &scc_info_FilterConfig_FilterMapEntry_DoNotUse_filter_5fdata_2eproto.base,}};

static void InitDefaultsscc_info_FilterConfig_FilterMapEntry_DoNotUse_filter_5fdata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::my_msg::_FilterConfig_FilterMapEntry_DoNotUse_default_instance_;
    new (ptr) ::my_msg::FilterConfig_FilterMapEntry_DoNotUse();
  }
  ::my_msg::FilterConfig_FilterMapEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_FilterConfig_FilterMapEntry_DoNotUse_filter_5fdata_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_FilterConfig_FilterMapEntry_DoNotUse_filter_5fdata_2eproto}, {
      &scc_info_FilterItem_filter_5fdata_2eproto.base,}};

static void InitDefaultsscc_info_FilterItem_filter_5fdata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::my_msg::_FilterItem_default_instance_;
    new (ptr) ::my_msg::FilterItem();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::my_msg::FilterItem::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FilterItem_filter_5fdata_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_FilterItem_filter_5fdata_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_filter_5fdata_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_filter_5fdata_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_filter_5fdata_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_filter_5fdata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::my_msg::FilterItem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::my_msg::FilterItem, include_filters_),
  PROTOBUF_FIELD_OFFSET(::my_msg::FilterItem, exclude_filters_),
  PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig_FilterMapEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig_FilterMapEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig_FilterMapEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig_FilterMapEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig, filter_map_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::my_msg::FilterItem)},
  { 7, 14, sizeof(::my_msg::FilterConfig_FilterMapEntry_DoNotUse)},
  { 16, -1, sizeof(::my_msg::FilterConfig)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::my_msg::_FilterItem_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::my_msg::_FilterConfig_FilterMapEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::my_msg::_FilterConfig_default_instance_),
};

const char descriptor_table_protodef_filter_5fdata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021filter_data.proto\022\006my_msg\">\n\nFilterIte"
  "m\022\027\n\017include_filters\030\001 \003(\t\022\027\n\017exclude_fi"
  "lters\030\002 \003(\t\"\215\001\n\014FilterConfig\0227\n\nfilter_m"
  "ap\030\001 \003(\0132#.my_msg.FilterConfig.FilterMap"
  "Entry\032D\n\016FilterMapEntry\022\013\n\003key\030\001 \001(\t\022!\n\005"
  "value\030\002 \001(\0132\022.my_msg.FilterItem:\0028\001b\006pro"
  "to3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_filter_5fdata_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_filter_5fdata_2eproto_sccs[3] = {
  &scc_info_FilterConfig_filter_5fdata_2eproto.base,
  &scc_info_FilterConfig_FilterMapEntry_DoNotUse_filter_5fdata_2eproto.base,
  &scc_info_FilterItem_filter_5fdata_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_filter_5fdata_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_filter_5fdata_2eproto = {
  false, false, descriptor_table_protodef_filter_5fdata_2eproto, "filter_data.proto", 243,
  &descriptor_table_filter_5fdata_2eproto_once, descriptor_table_filter_5fdata_2eproto_sccs, descriptor_table_filter_5fdata_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_filter_5fdata_2eproto::offsets,
  file_level_metadata_filter_5fdata_2eproto, 3, file_level_enum_descriptors_filter_5fdata_2eproto, file_level_service_descriptors_filter_5fdata_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_filter_5fdata_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_filter_5fdata_2eproto)), true);
namespace my_msg {

// ===================================================================

void FilterItem::InitAsDefaultInstance() {
}
class FilterItem::_Internal {
 public:
};

FilterItem::FilterItem(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  include_filters_(arena),
  exclude_filters_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:my_msg.FilterItem)
}
FilterItem::FilterItem(const FilterItem& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      include_filters_(from.include_filters_),
      exclude_filters_(from.exclude_filters_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:my_msg.FilterItem)
}

void FilterItem::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_FilterItem_filter_5fdata_2eproto.base);
}

FilterItem::~FilterItem() {
  // @@protoc_insertion_point(destructor:my_msg.FilterItem)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FilterItem::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void FilterItem::ArenaDtor(void* object) {
  FilterItem* _this = reinterpret_cast< FilterItem* >(object);
  (void)_this;
}
void FilterItem::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FilterItem::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FilterItem& FilterItem::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FilterItem_filter_5fdata_2eproto.base);
  return *internal_default_instance();
}


void FilterItem::Clear() {
// @@protoc_insertion_point(message_clear_start:my_msg.FilterItem)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  include_filters_.Clear();
  exclude_filters_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FilterItem::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated string include_filters = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_include_filters();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "my_msg.FilterItem.include_filters"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated string exclude_filters = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_exclude_filters();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "my_msg.FilterItem.exclude_filters"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FilterItem::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:my_msg.FilterItem)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string include_filters = 1;
  for (int i = 0, n = this->_internal_include_filters_size(); i < n; i++) {
    const auto& s = this->_internal_include_filters(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "my_msg.FilterItem.include_filters");
    target = stream->WriteString(1, s, target);
  }

  // repeated string exclude_filters = 2;
  for (int i = 0, n = this->_internal_exclude_filters_size(); i < n; i++) {
    const auto& s = this->_internal_exclude_filters(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "my_msg.FilterItem.exclude_filters");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:my_msg.FilterItem)
  return target;
}

size_t FilterItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:my_msg.FilterItem)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string include_filters = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(include_filters_.size());
  for (int i = 0, n = include_filters_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      include_filters_.Get(i));
  }

  // repeated string exclude_filters = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(exclude_filters_.size());
  for (int i = 0, n = exclude_filters_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      exclude_filters_.Get(i));
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FilterItem::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:my_msg.FilterItem)
  GOOGLE_DCHECK_NE(&from, this);
  const FilterItem* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FilterItem>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:my_msg.FilterItem)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:my_msg.FilterItem)
    MergeFrom(*source);
  }
}

void FilterItem::MergeFrom(const FilterItem& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:my_msg.FilterItem)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  include_filters_.MergeFrom(from.include_filters_);
  exclude_filters_.MergeFrom(from.exclude_filters_);
}

void FilterItem::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:my_msg.FilterItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FilterItem::CopyFrom(const FilterItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my_msg.FilterItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FilterItem::IsInitialized() const {
  return true;
}

void FilterItem::InternalSwap(FilterItem* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  include_filters_.InternalSwap(&other->include_filters_);
  exclude_filters_.InternalSwap(&other->exclude_filters_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FilterItem::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

FilterConfig_FilterMapEntry_DoNotUse::FilterConfig_FilterMapEntry_DoNotUse() {}
FilterConfig_FilterMapEntry_DoNotUse::FilterConfig_FilterMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void FilterConfig_FilterMapEntry_DoNotUse::MergeFrom(const FilterConfig_FilterMapEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata FilterConfig_FilterMapEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void FilterConfig_FilterMapEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

void FilterConfig::InitAsDefaultInstance() {
}
class FilterConfig::_Internal {
 public:
};

FilterConfig::FilterConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  filter_map_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:my_msg.FilterConfig)
}
FilterConfig::FilterConfig(const FilterConfig& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  filter_map_.MergeFrom(from.filter_map_);
  // @@protoc_insertion_point(copy_constructor:my_msg.FilterConfig)
}

void FilterConfig::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_FilterConfig_filter_5fdata_2eproto.base);
}

FilterConfig::~FilterConfig() {
  // @@protoc_insertion_point(destructor:my_msg.FilterConfig)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FilterConfig::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void FilterConfig::ArenaDtor(void* object) {
  FilterConfig* _this = reinterpret_cast< FilterConfig* >(object);
  (void)_this;
}
void FilterConfig::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FilterConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FilterConfig& FilterConfig::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FilterConfig_filter_5fdata_2eproto.base);
  return *internal_default_instance();
}


void FilterConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:my_msg.FilterConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  filter_map_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FilterConfig::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // map<string, .my_msg.FilterItem> filter_map = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&filter_map_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FilterConfig::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:my_msg.FilterConfig)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .my_msg.FilterItem> filter_map = 1;
  if (!this->_internal_filter_map().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "my_msg.FilterConfig.FilterMapEntry.key");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_filter_map().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_filter_map().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >::const_iterator
          it = this->_internal_filter_map().begin();
          it != this->_internal_filter_map().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = FilterConfig_FilterMapEntry_DoNotUse::Funcs::InternalSerialize(1, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >::const_iterator
          it = this->_internal_filter_map().begin();
          it != this->_internal_filter_map().end(); ++it) {
        target = FilterConfig_FilterMapEntry_DoNotUse::Funcs::InternalSerialize(1, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:my_msg.FilterConfig)
  return target;
}

size_t FilterConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:my_msg.FilterConfig)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .my_msg.FilterItem> filter_map = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_filter_map_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >::const_iterator
      it = this->_internal_filter_map().begin();
      it != this->_internal_filter_map().end(); ++it) {
    total_size += FilterConfig_FilterMapEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FilterConfig::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:my_msg.FilterConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const FilterConfig* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FilterConfig>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:my_msg.FilterConfig)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:my_msg.FilterConfig)
    MergeFrom(*source);
  }
}

void FilterConfig::MergeFrom(const FilterConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:my_msg.FilterConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  filter_map_.MergeFrom(from.filter_map_);
}

void FilterConfig::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:my_msg.FilterConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FilterConfig::CopyFrom(const FilterConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my_msg.FilterConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FilterConfig::IsInitialized() const {
  return true;
}

void FilterConfig::InternalSwap(FilterConfig* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  filter_map_.Swap(&other->filter_map_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FilterConfig::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace my_msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::my_msg::FilterItem* Arena::CreateMaybeMessage< ::my_msg::FilterItem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::my_msg::FilterItem >(arena);
}
template<> PROTOBUF_NOINLINE ::my_msg::FilterConfig_FilterMapEntry_DoNotUse* Arena::CreateMaybeMessage< ::my_msg::FilterConfig_FilterMapEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::my_msg::FilterConfig_FilterMapEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::my_msg::FilterConfig* Arena::CreateMaybeMessage< ::my_msg::FilterConfig >(Arena* arena) {
  return Arena::CreateMessageInternal< ::my_msg::FilterConfig >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
