// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filter_data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_filter_5fdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_filter_5fdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_filter_5fdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_filter_5fdata_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_filter_5fdata_2eproto;
namespace my_msg {
class FilterConfig;
class FilterConfigDefaultTypeInternal;
extern FilterConfigDefaultTypeInternal _FilterConfig_default_instance_;
class FilterConfig_FilterMapEntry_DoNotUse;
class FilterConfig_FilterMapEntry_DoNotUseDefaultTypeInternal;
extern FilterConfig_FilterMapEntry_DoNotUseDefaultTypeInternal _FilterConfig_FilterMapEntry_DoNotUse_default_instance_;
class FilterItem;
class FilterItemDefaultTypeInternal;
extern FilterItemDefaultTypeInternal _FilterItem_default_instance_;
}  // namespace my_msg
PROTOBUF_NAMESPACE_OPEN
template<> ::my_msg::FilterConfig* Arena::CreateMaybeMessage<::my_msg::FilterConfig>(Arena*);
template<> ::my_msg::FilterConfig_FilterMapEntry_DoNotUse* Arena::CreateMaybeMessage<::my_msg::FilterConfig_FilterMapEntry_DoNotUse>(Arena*);
template<> ::my_msg::FilterItem* Arena::CreateMaybeMessage<::my_msg::FilterItem>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace my_msg {

// ===================================================================

class FilterItem PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:my_msg.FilterItem) */ {
 public:
  inline FilterItem() : FilterItem(nullptr) {};
  virtual ~FilterItem();

  FilterItem(const FilterItem& from);
  FilterItem(FilterItem&& from) noexcept
    : FilterItem() {
    *this = ::std::move(from);
  }

  inline FilterItem& operator=(const FilterItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline FilterItem& operator=(FilterItem&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FilterItem& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FilterItem* internal_default_instance() {
    return reinterpret_cast<const FilterItem*>(
               &_FilterItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FilterItem& a, FilterItem& b) {
    a.Swap(&b);
  }
  inline void Swap(FilterItem* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FilterItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FilterItem* New() const final {
    return CreateMaybeMessage<FilterItem>(nullptr);
  }

  FilterItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FilterItem>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FilterItem& from);
  void MergeFrom(const FilterItem& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FilterItem* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "my_msg.FilterItem";
  }
  protected:
  explicit FilterItem(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_filter_5fdata_2eproto);
    return ::descriptor_table_filter_5fdata_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIncludeFiltersFieldNumber = 1,
    kExcludeFiltersFieldNumber = 2,
  };
  // repeated string include_filters = 1;
  int include_filters_size() const;
  private:
  int _internal_include_filters_size() const;
  public:
  void clear_include_filters();
  const std::string& include_filters(int index) const;
  std::string* mutable_include_filters(int index);
  void set_include_filters(int index, const std::string& value);
  void set_include_filters(int index, std::string&& value);
  void set_include_filters(int index, const char* value);
  void set_include_filters(int index, const char* value, size_t size);
  std::string* add_include_filters();
  void add_include_filters(const std::string& value);
  void add_include_filters(std::string&& value);
  void add_include_filters(const char* value);
  void add_include_filters(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& include_filters() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_include_filters();
  private:
  const std::string& _internal_include_filters(int index) const;
  std::string* _internal_add_include_filters();
  public:

  // repeated string exclude_filters = 2;
  int exclude_filters_size() const;
  private:
  int _internal_exclude_filters_size() const;
  public:
  void clear_exclude_filters();
  const std::string& exclude_filters(int index) const;
  std::string* mutable_exclude_filters(int index);
  void set_exclude_filters(int index, const std::string& value);
  void set_exclude_filters(int index, std::string&& value);
  void set_exclude_filters(int index, const char* value);
  void set_exclude_filters(int index, const char* value, size_t size);
  std::string* add_exclude_filters();
  void add_exclude_filters(const std::string& value);
  void add_exclude_filters(std::string&& value);
  void add_exclude_filters(const char* value);
  void add_exclude_filters(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& exclude_filters() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_exclude_filters();
  private:
  const std::string& _internal_exclude_filters(int index) const;
  std::string* _internal_add_exclude_filters();
  public:

  // @@protoc_insertion_point(class_scope:my_msg.FilterItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> include_filters_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> exclude_filters_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_filter_5fdata_2eproto;
};
// -------------------------------------------------------------------

class FilterConfig_FilterMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<FilterConfig_FilterMapEntry_DoNotUse, 
    std::string, ::my_msg::FilterItem,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<FilterConfig_FilterMapEntry_DoNotUse, 
    std::string, ::my_msg::FilterItem,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  FilterConfig_FilterMapEntry_DoNotUse();
  explicit FilterConfig_FilterMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const FilterConfig_FilterMapEntry_DoNotUse& other);
  static const FilterConfig_FilterMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const FilterConfig_FilterMapEntry_DoNotUse*>(&_FilterConfig_FilterMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "my_msg.FilterConfig.FilterMapEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_filter_5fdata_2eproto);
    return ::descriptor_table_filter_5fdata_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class FilterConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:my_msg.FilterConfig) */ {
 public:
  inline FilterConfig() : FilterConfig(nullptr) {};
  virtual ~FilterConfig();

  FilterConfig(const FilterConfig& from);
  FilterConfig(FilterConfig&& from) noexcept
    : FilterConfig() {
    *this = ::std::move(from);
  }

  inline FilterConfig& operator=(const FilterConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline FilterConfig& operator=(FilterConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FilterConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FilterConfig* internal_default_instance() {
    return reinterpret_cast<const FilterConfig*>(
               &_FilterConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FilterConfig& a, FilterConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(FilterConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FilterConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FilterConfig* New() const final {
    return CreateMaybeMessage<FilterConfig>(nullptr);
  }

  FilterConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FilterConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FilterConfig& from);
  void MergeFrom(const FilterConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FilterConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "my_msg.FilterConfig";
  }
  protected:
  explicit FilterConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_filter_5fdata_2eproto);
    return ::descriptor_table_filter_5fdata_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kFilterMapFieldNumber = 1,
  };
  // map<string, .my_msg.FilterItem> filter_map = 1;
  int filter_map_size() const;
  private:
  int _internal_filter_map_size() const;
  public:
  void clear_filter_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >&
      _internal_filter_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >*
      _internal_mutable_filter_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >&
      filter_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >*
      mutable_filter_map();

  // @@protoc_insertion_point(class_scope:my_msg.FilterConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      FilterConfig_FilterMapEntry_DoNotUse,
      std::string, ::my_msg::FilterItem,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE,
      0 > filter_map_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_filter_5fdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FilterItem

// repeated string include_filters = 1;
inline int FilterItem::_internal_include_filters_size() const {
  return include_filters_.size();
}
inline int FilterItem::include_filters_size() const {
  return _internal_include_filters_size();
}
inline void FilterItem::clear_include_filters() {
  include_filters_.Clear();
}
inline std::string* FilterItem::add_include_filters() {
  // @@protoc_insertion_point(field_add_mutable:my_msg.FilterItem.include_filters)
  return _internal_add_include_filters();
}
inline const std::string& FilterItem::_internal_include_filters(int index) const {
  return include_filters_.Get(index);
}
inline const std::string& FilterItem::include_filters(int index) const {
  // @@protoc_insertion_point(field_get:my_msg.FilterItem.include_filters)
  return _internal_include_filters(index);
}
inline std::string* FilterItem::mutable_include_filters(int index) {
  // @@protoc_insertion_point(field_mutable:my_msg.FilterItem.include_filters)
  return include_filters_.Mutable(index);
}
inline void FilterItem::set_include_filters(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:my_msg.FilterItem.include_filters)
  include_filters_.Mutable(index)->assign(value);
}
inline void FilterItem::set_include_filters(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:my_msg.FilterItem.include_filters)
  include_filters_.Mutable(index)->assign(std::move(value));
}
inline void FilterItem::set_include_filters(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  include_filters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:my_msg.FilterItem.include_filters)
}
inline void FilterItem::set_include_filters(int index, const char* value, size_t size) {
  include_filters_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:my_msg.FilterItem.include_filters)
}
inline std::string* FilterItem::_internal_add_include_filters() {
  return include_filters_.Add();
}
inline void FilterItem::add_include_filters(const std::string& value) {
  include_filters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:my_msg.FilterItem.include_filters)
}
inline void FilterItem::add_include_filters(std::string&& value) {
  include_filters_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:my_msg.FilterItem.include_filters)
}
inline void FilterItem::add_include_filters(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  include_filters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:my_msg.FilterItem.include_filters)
}
inline void FilterItem::add_include_filters(const char* value, size_t size) {
  include_filters_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:my_msg.FilterItem.include_filters)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
FilterItem::include_filters() const {
  // @@protoc_insertion_point(field_list:my_msg.FilterItem.include_filters)
  return include_filters_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
FilterItem::mutable_include_filters() {
  // @@protoc_insertion_point(field_mutable_list:my_msg.FilterItem.include_filters)
  return &include_filters_;
}

// repeated string exclude_filters = 2;
inline int FilterItem::_internal_exclude_filters_size() const {
  return exclude_filters_.size();
}
inline int FilterItem::exclude_filters_size() const {
  return _internal_exclude_filters_size();
}
inline void FilterItem::clear_exclude_filters() {
  exclude_filters_.Clear();
}
inline std::string* FilterItem::add_exclude_filters() {
  // @@protoc_insertion_point(field_add_mutable:my_msg.FilterItem.exclude_filters)
  return _internal_add_exclude_filters();
}
inline const std::string& FilterItem::_internal_exclude_filters(int index) const {
  return exclude_filters_.Get(index);
}
inline const std::string& FilterItem::exclude_filters(int index) const {
  // @@protoc_insertion_point(field_get:my_msg.FilterItem.exclude_filters)
  return _internal_exclude_filters(index);
}
inline std::string* FilterItem::mutable_exclude_filters(int index) {
  // @@protoc_insertion_point(field_mutable:my_msg.FilterItem.exclude_filters)
  return exclude_filters_.Mutable(index);
}
inline void FilterItem::set_exclude_filters(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:my_msg.FilterItem.exclude_filters)
  exclude_filters_.Mutable(index)->assign(value);
}
inline void FilterItem::set_exclude_filters(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:my_msg.FilterItem.exclude_filters)
  exclude_filters_.Mutable(index)->assign(std::move(value));
}
inline void FilterItem::set_exclude_filters(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  exclude_filters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:my_msg.FilterItem.exclude_filters)
}
inline void FilterItem::set_exclude_filters(int index, const char* value, size_t size) {
  exclude_filters_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:my_msg.FilterItem.exclude_filters)
}
inline std::string* FilterItem::_internal_add_exclude_filters() {
  return exclude_filters_.Add();
}
inline void FilterItem::add_exclude_filters(const std::string& value) {
  exclude_filters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:my_msg.FilterItem.exclude_filters)
}
inline void FilterItem::add_exclude_filters(std::string&& value) {
  exclude_filters_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:my_msg.FilterItem.exclude_filters)
}
inline void FilterItem::add_exclude_filters(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  exclude_filters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:my_msg.FilterItem.exclude_filters)
}
inline void FilterItem::add_exclude_filters(const char* value, size_t size) {
  exclude_filters_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:my_msg.FilterItem.exclude_filters)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
FilterItem::exclude_filters() const {
  // @@protoc_insertion_point(field_list:my_msg.FilterItem.exclude_filters)
  return exclude_filters_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
FilterItem::mutable_exclude_filters() {
  // @@protoc_insertion_point(field_mutable_list:my_msg.FilterItem.exclude_filters)
  return &exclude_filters_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// FilterConfig

// map<string, .my_msg.FilterItem> filter_map = 1;
inline int FilterConfig::_internal_filter_map_size() const {
  return filter_map_.size();
}
inline int FilterConfig::filter_map_size() const {
  return _internal_filter_map_size();
}
inline void FilterConfig::clear_filter_map() {
  filter_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >&
FilterConfig::_internal_filter_map() const {
  return filter_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >&
FilterConfig::filter_map() const {
  // @@protoc_insertion_point(field_map:my_msg.FilterConfig.filter_map)
  return _internal_filter_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >*
FilterConfig::_internal_mutable_filter_map() {
  return filter_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::my_msg::FilterItem >*
FilterConfig::mutable_filter_map() {
  // @@protoc_insertion_point(field_mutable_map:my_msg.FilterConfig.filter_map)
  return _internal_mutable_filter_map();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace my_msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_filter_5fdata_2eproto
