// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: filter_data.proto
// Protobuf C++ Version: 6.33.4

#ifndef filter_5fdata_2eproto_2epb_2eh
#define filter_5fdata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_filter_5fdata_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_filter_5fdata_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_filter_5fdata_2eproto;
}  // extern "C"
namespace my_msg {
class FilterConfig;
struct FilterConfigDefaultTypeInternal;
extern FilterConfigDefaultTypeInternal _FilterConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FilterConfig_class_data_;
class FilterConfig_FilterMapEntry_DoNotUse;
struct FilterConfig_FilterMapEntry_DoNotUseDefaultTypeInternal;
extern FilterConfig_FilterMapEntry_DoNotUseDefaultTypeInternal _FilterConfig_FilterMapEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FilterConfig_FilterMapEntry_DoNotUse_class_data_;
class FilterItem;
struct FilterItemDefaultTypeInternal;
extern FilterItemDefaultTypeInternal _FilterItem_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FilterItem_class_data_;
}  // namespace my_msg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace my_msg {

// ===================================================================


// -------------------------------------------------------------------

class FilterItem final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:my_msg.FilterItem) */ {
 public:
  inline FilterItem() : FilterItem(nullptr) {}
  ~FilterItem() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FilterItem* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FilterItem));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FilterItem(::google::protobuf::internal::ConstantInitialized);

  inline FilterItem(const FilterItem& from) : FilterItem(nullptr, from) {}
  inline FilterItem(FilterItem&& from) noexcept
      : FilterItem(nullptr, ::std::move(from)) {}
  inline FilterItem& operator=(const FilterItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline FilterItem& operator=(FilterItem&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FilterItem& default_instance() {
    return *reinterpret_cast<const FilterItem*>(
        &_FilterItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(FilterItem& a, FilterItem& b) { a.Swap(&b); }
  inline void Swap(FilterItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FilterItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FilterItem* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FilterItem>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FilterItem& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FilterItem& from) { FilterItem::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FilterItem* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "my_msg.FilterItem"; }

  explicit FilterItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FilterItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FilterItem& from);
  FilterItem(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FilterItem&& from) noexcept
      : FilterItem(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIncludeFiltersFieldNumber = 1,
    kExcludeFiltersFieldNumber = 2,
  };
  // repeated string include_filters = 1;
  int include_filters_size() const;
  private:
  int _internal_include_filters_size() const;

  public:
  void clear_include_filters() ;
  const ::std::string& include_filters(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_include_filters(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_include_filters(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_include_filters();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_include_filters(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& include_filters() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_include_filters();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_include_filters() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_include_filters();

  public:
  // repeated string exclude_filters = 2;
  int exclude_filters_size() const;
  private:
  int _internal_exclude_filters_size() const;

  public:
  void clear_exclude_filters() ;
  const ::std::string& exclude_filters(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_exclude_filters(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_exclude_filters(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_exclude_filters();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_exclude_filters(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& exclude_filters() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_exclude_filters();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_exclude_filters() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_exclude_filters();

  public:
  // @@protoc_insertion_point(class_scope:my_msg.FilterItem)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 56,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FilterItem& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> include_filters_;
    ::google::protobuf::RepeatedPtrField<::std::string> exclude_filters_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_filter_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FilterItem_class_data_;
// -------------------------------------------------------------------

class FilterConfig_FilterMapEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::google::protobuf::Message,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::google::protobuf::Message,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>;
  FilterConfig_FilterMapEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FilterConfig_FilterMapEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit FilterConfig_FilterMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_FilterConfig_FilterMapEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_filter_5fdata_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 46,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull FilterConfig_FilterMapEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class FilterConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:my_msg.FilterConfig) */ {
 public:
  inline FilterConfig() : FilterConfig(nullptr) {}
  ~FilterConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FilterConfig* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FilterConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FilterConfig(::google::protobuf::internal::ConstantInitialized);

  inline FilterConfig(const FilterConfig& from) : FilterConfig(nullptr, from) {}
  inline FilterConfig(FilterConfig&& from) noexcept
      : FilterConfig(nullptr, ::std::move(from)) {}
  inline FilterConfig& operator=(const FilterConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline FilterConfig& operator=(FilterConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FilterConfig& default_instance() {
    return *reinterpret_cast<const FilterConfig*>(
        &_FilterConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(FilterConfig& a, FilterConfig& b) { a.Swap(&b); }
  inline void Swap(FilterConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FilterConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FilterConfig* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FilterConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FilterConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FilterConfig& from) { FilterConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FilterConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "my_msg.FilterConfig"; }

  explicit FilterConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FilterConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FilterConfig& from);
  FilterConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FilterConfig&& from) noexcept
      : FilterConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFilterMapFieldNumber = 1,
  };
  // map<string, .my_msg.FilterItem> filter_map = 1;
  int filter_map_size() const;
  private:
  int _internal_filter_map_size() const;

  public:
  void clear_filter_map() ;
  const ::google::protobuf::Map<::std::string, ::my_msg::FilterItem>& filter_map() const;
  ::google::protobuf::Map<::std::string, ::my_msg::FilterItem>* PROTOBUF_NONNULL mutable_filter_map();

  private:
  const ::google::protobuf::Map<::std::string, ::my_msg::FilterItem>& _internal_filter_map() const;
  ::google::protobuf::Map<::std::string, ::my_msg::FilterItem>* PROTOBUF_NONNULL _internal_mutable_filter_map();

  public:
  // @@protoc_insertion_point(class_scope:my_msg.FilterConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   2, 38,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FilterConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<FilterConfig_FilterMapEntry_DoNotUse, ::std::string, ::my_msg::FilterItem,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE>
        filter_map_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_filter_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FilterConfig_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// FilterItem

// repeated string include_filters = 1;
inline int FilterItem::_internal_include_filters_size() const {
  return _internal_include_filters().size();
}
inline int FilterItem::include_filters_size() const {
  return _internal_include_filters_size();
}
inline void FilterItem::clear_include_filters() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.include_filters_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL FilterItem::add_include_filters()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_include_filters()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:my_msg.FilterItem.include_filters)
  return _s;
}
inline const ::std::string& FilterItem::include_filters(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:my_msg.FilterItem.include_filters)
  return _internal_include_filters().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL FilterItem::mutable_include_filters(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:my_msg.FilterItem.include_filters)
  return _internal_mutable_include_filters()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void FilterItem::set_include_filters(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_include_filters()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:my_msg.FilterItem.include_filters)
}
template <typename Arg_, typename... Args_>
inline void FilterItem::add_include_filters(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_include_filters(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:my_msg.FilterItem.include_filters)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& FilterItem::include_filters()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:my_msg.FilterItem.include_filters)
  return _internal_include_filters();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
FilterItem::mutable_include_filters() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:my_msg.FilterItem.include_filters)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_include_filters();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
FilterItem::_internal_include_filters() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.include_filters_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
FilterItem::_internal_mutable_include_filters() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.include_filters_;
}

// repeated string exclude_filters = 2;
inline int FilterItem::_internal_exclude_filters_size() const {
  return _internal_exclude_filters().size();
}
inline int FilterItem::exclude_filters_size() const {
  return _internal_exclude_filters_size();
}
inline void FilterItem::clear_exclude_filters() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exclude_filters_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::std::string* PROTOBUF_NONNULL FilterItem::add_exclude_filters()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_exclude_filters()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add_mutable:my_msg.FilterItem.exclude_filters)
  return _s;
}
inline const ::std::string& FilterItem::exclude_filters(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:my_msg.FilterItem.exclude_filters)
  return _internal_exclude_filters().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL FilterItem::mutable_exclude_filters(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:my_msg.FilterItem.exclude_filters)
  return _internal_mutable_exclude_filters()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void FilterItem::set_exclude_filters(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_exclude_filters()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:my_msg.FilterItem.exclude_filters)
}
template <typename Arg_, typename... Args_>
inline void FilterItem::add_exclude_filters(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_exclude_filters(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:my_msg.FilterItem.exclude_filters)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& FilterItem::exclude_filters()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:my_msg.FilterItem.exclude_filters)
  return _internal_exclude_filters();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
FilterItem::mutable_exclude_filters() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:my_msg.FilterItem.exclude_filters)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_exclude_filters();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
FilterItem::_internal_exclude_filters() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exclude_filters_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
FilterItem::_internal_mutable_exclude_filters() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.exclude_filters_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// FilterConfig

// map<string, .my_msg.FilterItem> filter_map = 1;
inline int FilterConfig::_internal_filter_map_size() const {
  return _internal_filter_map().size();
}
inline int FilterConfig::filter_map_size() const {
  return _internal_filter_map_size();
}
inline void FilterConfig::clear_filter_map() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filter_map_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::google::protobuf::Map<::std::string, ::my_msg::FilterItem>& FilterConfig::_internal_filter_map() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filter_map_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::my_msg::FilterItem>& FilterConfig::filter_map() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:my_msg.FilterConfig.filter_map)
  return _internal_filter_map();
}
inline ::google::protobuf::Map<::std::string, ::my_msg::FilterItem>* PROTOBUF_NONNULL FilterConfig::_internal_mutable_filter_map() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.filter_map_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::my_msg::FilterItem>* PROTOBUF_NONNULL FilterConfig::mutable_filter_map()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_map:my_msg.FilterConfig.filter_map)
  return _internal_mutable_filter_map();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace my_msg


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // filter_5fdata_2eproto_2epb_2eh
