// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: filter_data.proto
// Protobuf C++ Version: 6.33.4

#include "filter_data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace my_msg {

inline constexpr FilterItem::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        include_filters_{},
        exclude_filters_{} {}

template <typename>
PROTOBUF_CONSTEXPR FilterItem::FilterItem(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(FilterItem_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FilterItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FilterItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FilterItemDefaultTypeInternal() {}
  union {
    FilterItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FilterItemDefaultTypeInternal _FilterItem_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR FilterConfig_FilterMapEntry_DoNotUse::FilterConfig_FilterMapEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : FilterConfig_FilterMapEntry_DoNotUse::MapEntry(FilterConfig_FilterMapEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : FilterConfig_FilterMapEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct FilterConfig_FilterMapEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FilterConfig_FilterMapEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FilterConfig_FilterMapEntry_DoNotUseDefaultTypeInternal() {}
  union {
    FilterConfig_FilterMapEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FilterConfig_FilterMapEntry_DoNotUseDefaultTypeInternal _FilterConfig_FilterMapEntry_DoNotUse_default_instance_;

inline constexpr FilterConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        filter_map_{} {}

template <typename>
PROTOBUF_CONSTEXPR FilterConfig::FilterConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(FilterConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FilterConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FilterConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FilterConfigDefaultTypeInternal() {}
  union {
    FilterConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FilterConfigDefaultTypeInternal _FilterConfig_default_instance_;
}  // namespace my_msg
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_filter_5fdata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_filter_5fdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_filter_5fdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::my_msg::FilterItem, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::my_msg::FilterItem, _impl_.include_filters_),
        PROTOBUF_FIELD_OFFSET(::my_msg::FilterItem, _impl_.exclude_filters_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig_FilterMapEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig_FilterMapEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig_FilterMapEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::my_msg::FilterConfig, _impl_.filter_map_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::my_msg::FilterItem)},
        {7, sizeof(::my_msg::FilterConfig_FilterMapEntry_DoNotUse)},
        {14, sizeof(::my_msg::FilterConfig)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::my_msg::_FilterItem_default_instance_._instance,
    &::my_msg::_FilterConfig_FilterMapEntry_DoNotUse_default_instance_._instance,
    &::my_msg::_FilterConfig_default_instance_._instance,
};
const char descriptor_table_protodef_filter_5fdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021filter_data.proto\022\006my_msg\">\n\nFilterIte"
    "m\022\027\n\017include_filters\030\001 \003(\t\022\027\n\017exclude_fi"
    "lters\030\002 \003(\t\"\215\001\n\014FilterConfig\0227\n\nfilter_m"
    "ap\030\001 \003(\0132#.my_msg.FilterConfig.FilterMap"
    "Entry\032D\n\016FilterMapEntry\022\013\n\003key\030\001 \001(\t\022!\n\005"
    "value\030\002 \001(\0132\022.my_msg.FilterItem:\0028\001b\006pro"
    "to3"
};
static ::absl::once_flag descriptor_table_filter_5fdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_filter_5fdata_2eproto = {
    false,
    false,
    243,
    descriptor_table_protodef_filter_5fdata_2eproto,
    "filter_data.proto",
    &descriptor_table_filter_5fdata_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_filter_5fdata_2eproto::offsets,
    file_level_enum_descriptors_filter_5fdata_2eproto,
    file_level_service_descriptors_filter_5fdata_2eproto,
};
namespace my_msg {
// ===================================================================

class FilterItem::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<FilterItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FilterItem, _impl_._has_bits_);
};

FilterItem::FilterItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FilterItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:my_msg.FilterItem)
}
PROTOBUF_NDEBUG_INLINE FilterItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::my_msg::FilterItem& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        include_filters_{visibility, arena, from.include_filters_},
        exclude_filters_{visibility, arena, from.exclude_filters_} {}

FilterItem::FilterItem(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const FilterItem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FilterItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FilterItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:my_msg.FilterItem)
}
PROTOBUF_NDEBUG_INLINE FilterItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        include_filters_{visibility, arena},
        exclude_filters_{visibility, arena} {}

inline void FilterItem::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FilterItem::~FilterItem() {
  // @@protoc_insertion_point(destructor:my_msg.FilterItem)
  SharedDtor(*this);
}
inline void FilterItem::SharedDtor(MessageLite& self) {
  FilterItem& this_ = static_cast<FilterItem&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL FilterItem::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FilterItem(arena);
}
constexpr auto FilterItem::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(FilterItem, _impl_.include_filters_) +
          decltype(FilterItem::_impl_.include_filters_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(FilterItem, _impl_.exclude_filters_) +
          decltype(FilterItem::_impl_.exclude_filters_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(FilterItem), alignof(FilterItem), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&FilterItem::PlacementNew_,
                                 sizeof(FilterItem),
                                 alignof(FilterItem));
  }
}
constexpr auto FilterItem::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_FilterItem_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FilterItem::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FilterItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FilterItem::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FilterItem>(), &FilterItem::ByteSizeLong,
              &FilterItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FilterItem, _impl_._cached_size_),
          false,
      },
      &FilterItem::kDescriptorMethods,
      &descriptor_table_filter_5fdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FilterItem_class_data_ =
        FilterItem::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FilterItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FilterItem_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FilterItem_class_data_.tc_table);
  return FilterItem_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 56, 2>
FilterItem::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FilterItem, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    FilterItem_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::my_msg::FilterItem>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string exclude_filters = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(FilterItem, _impl_.exclude_filters_)}},
    // repeated string include_filters = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(FilterItem, _impl_.include_filters_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string include_filters = 1;
    {PROTOBUF_FIELD_OFFSET(FilterItem, _impl_.include_filters_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string exclude_filters = 2;
    {PROTOBUF_FIELD_OFFSET(FilterItem, _impl_.exclude_filters_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\21\17\17\0\0\0\0\0"
    "my_msg.FilterItem"
    "include_filters"
    "exclude_filters"
  }},
};
PROTOBUF_NOINLINE void FilterItem::Clear() {
// @@protoc_insertion_point(message_clear_start:my_msg.FilterItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.include_filters_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.exclude_filters_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FilterItem::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FilterItem& this_ = static_cast<const FilterItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FilterItem::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FilterItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:my_msg.FilterItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated string include_filters = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_include_filters_size(); i < n; ++i) {
      const auto& s = this_._internal_include_filters().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_msg.FilterItem.include_filters");
      target = stream->WriteString(1, s, target);
    }
  }

  // repeated string exclude_filters = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (int i = 0, n = this_._internal_exclude_filters_size(); i < n; ++i) {
      const auto& s = this_._internal_exclude_filters().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_msg.FilterItem.exclude_filters");
      target = stream->WriteString(2, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:my_msg.FilterItem)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FilterItem::ByteSizeLong(const MessageLite& base) {
  const FilterItem& this_ = static_cast<const FilterItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FilterItem::ByteSizeLong() const {
  const FilterItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:my_msg.FilterItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated string include_filters = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_include_filters().size());
      for (int i = 0, n = this_._internal_include_filters().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_include_filters().Get(i));
      }
    }
    // repeated string exclude_filters = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_exclude_filters().size());
      for (int i = 0, n = this_._internal_exclude_filters().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_exclude_filters().Get(i));
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FilterItem::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<FilterItem*>(&to_msg);
  auto& from = static_cast<const FilterItem&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:my_msg.FilterItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_include_filters()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_include_filters());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_exclude_filters()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_exclude_filters());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FilterItem::CopyFrom(const FilterItem& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:my_msg.FilterItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FilterItem::InternalSwap(FilterItem* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.include_filters_.InternalSwap(&other->_impl_.include_filters_);
  _impl_.exclude_filters_.InternalSwap(&other->_impl_.exclude_filters_);
}

::google::protobuf::Metadata FilterItem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
FilterConfig_FilterMapEntry_DoNotUse::FilterConfig_FilterMapEntry_DoNotUse()
    : SuperType(FilterConfig_FilterMapEntry_DoNotUse_class_data_.base()) {}
FilterConfig_FilterMapEntry_DoNotUse::FilterConfig_FilterMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, FilterConfig_FilterMapEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
FilterConfig_FilterMapEntry_DoNotUse::FilterConfig_FilterMapEntry_DoNotUse() : SuperType() {}
FilterConfig_FilterMapEntry_DoNotUse::FilterConfig_FilterMapEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL FilterConfig_FilterMapEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FilterConfig_FilterMapEntry_DoNotUse(arena);
}
constexpr auto FilterConfig_FilterMapEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FilterConfig_FilterMapEntry_DoNotUse),
                                            alignof(FilterConfig_FilterMapEntry_DoNotUse));
}
constexpr auto FilterConfig_FilterMapEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_FilterConfig_FilterMapEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FilterConfig_FilterMapEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FilterConfig_FilterMapEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FilterConfig_FilterMapEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&FilterConfig_FilterMapEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FilterConfig_FilterMapEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &FilterConfig_FilterMapEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_filter_5fdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FilterConfig_FilterMapEntry_DoNotUse_class_data_ =
        FilterConfig_FilterMapEntry_DoNotUse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FilterConfig_FilterMapEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FilterConfig_FilterMapEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FilterConfig_FilterMapEntry_DoNotUse_class_data_.tc_table);
  return FilterConfig_FilterMapEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 46, 2>
FilterConfig_FilterMapEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FilterConfig_FilterMapEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    FilterConfig_FilterMapEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::my_msg::FilterConfig_FilterMapEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .my_msg.FilterItem value = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(FilterConfig_FilterMapEntry_DoNotUse, _impl_.value_)}},
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(FilterConfig_FilterMapEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(FilterConfig_FilterMapEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .my_msg.FilterItem value = 2;
    {PROTOBUF_FIELD_OFFSET(FilterConfig_FilterMapEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::my_msg::FilterItem>()},
  }},
  {{
    "\42\3\0\0\0\0\0\0"
    "my_msg.FilterConfig.FilterMapEntry"
    "key"
  }},
};
// ===================================================================

class FilterConfig::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<FilterConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FilterConfig, _impl_._has_bits_);
};

FilterConfig::FilterConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FilterConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:my_msg.FilterConfig)
}
PROTOBUF_NDEBUG_INLINE FilterConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::my_msg::FilterConfig& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        filter_map_{visibility, arena, from.filter_map_} {}

FilterConfig::FilterConfig(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const FilterConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FilterConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FilterConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:my_msg.FilterConfig)
}
PROTOBUF_NDEBUG_INLINE FilterConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        filter_map_{visibility, arena} {}

inline void FilterConfig::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FilterConfig::~FilterConfig() {
  // @@protoc_insertion_point(destructor:my_msg.FilterConfig)
  SharedDtor(*this);
}
inline void FilterConfig::SharedDtor(MessageLite& self) {
  FilterConfig& this_ = static_cast<FilterConfig&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL FilterConfig::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FilterConfig(arena);
}
constexpr auto FilterConfig::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(FilterConfig, _impl_.filter_map_) +
          decltype(FilterConfig::_impl_.filter_map_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(FilterConfig), alignof(FilterConfig), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&FilterConfig::PlacementNew_,
                                 sizeof(FilterConfig),
                                 alignof(FilterConfig));
  }
}
constexpr auto FilterConfig::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_FilterConfig_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FilterConfig::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FilterConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FilterConfig::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FilterConfig>(), &FilterConfig::ByteSizeLong,
              &FilterConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FilterConfig, _impl_._cached_size_),
          false,
      },
      &FilterConfig::kDescriptorMethods,
      &descriptor_table_filter_5fdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FilterConfig_class_data_ =
        FilterConfig::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FilterConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FilterConfig_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FilterConfig_class_data_.tc_table);
  return FilterConfig_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 2, 38, 2>
FilterConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FilterConfig, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    FilterConfig_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::my_msg::FilterConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<string, .my_msg.FilterItem> filter_map = 1;
    {PROTOBUF_FIELD_OFFSET(FilterConfig, _impl_.filter_map_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }},
  {{
      {::_pbi::TcParser::GetMapAuxInfo(
          1, 0, 9, 11, 0)},
      {::_pbi::TcParser::GetTable<::my_msg::FilterItem>()},
  }},
  {{
    "\23\12\0\0\0\0\0\0"
    "my_msg.FilterConfig"
    "filter_map"
  }},
};
PROTOBUF_NOINLINE void FilterConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:my_msg.FilterConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.filter_map_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FilterConfig::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FilterConfig& this_ = static_cast<const FilterConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FilterConfig::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FilterConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:my_msg.FilterConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // map<string, .my_msg.FilterItem> filter_map = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_filter_map().empty()) {
      using MapType = ::google::protobuf::Map<::std::string, ::my_msg::FilterItem>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::my_msg::FilterItem,
                                     _pbi::WireFormatLite::TYPE_STRING,
                                     _pbi::WireFormatLite::TYPE_MESSAGE>;
      const auto& field = this_._internal_filter_map();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              1, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_msg.FilterConfig.filter_map");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              1, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "my_msg.FilterConfig.filter_map");
        }
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:my_msg.FilterConfig)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FilterConfig::ByteSizeLong(const MessageLite& base) {
  const FilterConfig& this_ = static_cast<const FilterConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FilterConfig::ByteSizeLong() const {
  const FilterConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:my_msg.FilterConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // map<string, .my_msg.FilterItem> filter_map = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_filter_map_size());
      for (const auto& entry : this_._internal_filter_map()) {
        total_size += _pbi::MapEntryFuncs<::std::string, ::my_msg::FilterItem,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FilterConfig::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<FilterConfig*>(&to_msg);
  auto& from = static_cast<const FilterConfig&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:my_msg.FilterConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_impl_.filter_map_.MergeFrom(from._impl_.filter_map_);
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FilterConfig::CopyFrom(const FilterConfig& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:my_msg.FilterConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FilterConfig::InternalSwap(FilterConfig* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.filter_map_.InternalSwap(&other->_impl_.filter_map_);
}

::google::protobuf::Metadata FilterConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace my_msg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_filter_5fdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
